
  /follower:
    get:
     summary: Get all followers
     tags: [follower]
     responses:
       200:
        schema:
          $ref: '#/components/schemas/follower'
 
    post:
      summary: Create follower
      tags: [follower]
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/follower'
      responses:
        201:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/follower'
 
  /follower/{id}:
    get:
      summary: Get follower by id
      tags: [follower]
      parameters:
        - in: path
          name: id
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/follower'
 
    put:
      summary: Edit follower
      tags: [follower]
      parameters:
        - in: path
          name: id
      responses:
        202:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/follower'
      requestBody:
        content:
            application/json:
              schema:
               $ref: '#/components/schemas/follower'
 
    delete:
      summary: Delete follower
      tags: [follower]
      parameters:
        - in: path
          name: id
      responses:
        202:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/follower'

  /posts:
    get:
     summary: Get all postss
     tags: [posts]
     responses:
       200:
        schema:
          $ref: '#/components/schemas/posts'
 
    post:
      summary: Create posts
      tags: [posts]
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/posts'
      responses:
        201:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/posts'
 
  /posts/{id}:
    get:
      summary: Get posts by id
      tags: [posts]
      parameters:
        - in: path
          name: id
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/posts'
 
    put:
      summary: Edit posts
      tags: [posts]
      parameters:
        - in: path
          name: id
      responses:
        202:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/posts'
      requestBody:
        content:
            application/json:
              schema:
               $ref: '#/components/schemas/posts'
 
    delete:
      summary: Delete posts
      tags: [posts]
      parameters:
        - in: path
          name: id
      responses:
        202:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/posts'

  /user:
    get:
     summary: Get all users
     tags: [user]
     responses:
       200:
        schema:
          $ref: '#/components/schemas/user'
 
    post:
      summary: Create user
      tags: [user]
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/user'
      responses:
        201:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
 
  /user/{id}:
    get:
      summary: Get user by id
      tags: [user]
      parameters:
        - in: path
          name: id
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
 
    put:
      summary: Edit user
      tags: [user]
      parameters:
        - in: path
          name: id
      responses:
        202:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
      requestBody:
        content:
            application/json:
              schema:
               $ref: '#/components/schemas/user'
 
    delete:
      summary: Delete user
      tags: [user]
      parameters:
        - in: path
          name: id
      responses:
        202:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'

  components:
    schemas:
  
      follower:
        type: object
        properties:
      
          id:
            type: string
          user:
            type: string
      posts:
        type: object
        properties:
      
          id:
            type: string
          title:
            type: string
          content:
            type: string
          user:
            type: string
      user:
        type: object
        properties:
      
          id:
            type: number
          name:
            type: string
          email:
            type: string
          gender:
            type: string
          age:
            type: number
          password:
            type: string